//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountClient
    {
        public int Acc_ClientID { get; set; }
        public string ClientName { get; set; }
        public string CompanyName { get; set; }
        public string Email { get; set; }
        public string WebsiteUrl { get; set; }
        public string IndustryID { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> Acc_AccountID { get; set; }
    }
}
