//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountDepartment
    {
        public int AccountDepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public string Dept_Description { get; set; }
        public Nullable<System.DateTime> Dept_CreatedDate { get; set; }
        public Nullable<int> Dept_CreatedBy { get; set; }
        public Nullable<System.DateTime> Dept_ModifiedDate { get; set; }
        public Nullable<int> Dept_ModifiedBy { get; set; }
        public Nullable<bool> Dept_isDeleted { get; set; }
        public Nullable<bool> Dept_ActiveStatus { get; set; }
    }
}
