//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.HolidayCalendars = new HashSet<HolidayCalendar>();
            this.Roles = new HashSet<Role>();
            this.Users = new HashSet<User>();
            this.UserTypes = new HashSet<UserType>();
        }
    
        public int Acc_AccountID { get; set; }
        public string Acc_AccountCode { get; set; }
        public string Acc_AccountName { get; set; }
        public string Acc_AccountDescription { get; set; }
        public string Acc_EmailID { get; set; }
        public string Acc_MobileNumber { get; set; }
        public string Acc_PhoneNumber { get; set; }
        public string Acc_CompanyLogo { get; set; }
        public bool Acc_ActiveStatus { get; set; }
        public short Acc_Version { get; set; }
        public System.DateTime Acc_CreatedDate { get; set; }
        public int Acc_CreatedBy { get; set; }
        public Nullable<System.DateTime> Acc_ModifiedDate { get; set; }
        public Nullable<int> Acc_ModifiedBy { get; set; }
        public bool Acc_isDeleted { get; set; }
        public bool is_UsAccount { get; set; }
        public bool is_pre_requisite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HolidayCalendar> HolidayCalendars { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserType> UserTypes { get; set; }
    }
}
