//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttachmentsinTimesheet
    {
        public int AttachmentId { get; set; }
        public Nullable<int> TimeSheetID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UploadedImages { get; set; }
    
        public virtual TIMESHEET TIMESHEET { get; set; }
        public virtual TIMESHEET TIMESHEET1 { get; set; }
    }
}
