//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateInterviewResult
    {
        public int CIRID { get; set; }
        public Nullable<int> Candidateid { get; set; }
        public Nullable<int> Questionid { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> SelectedOption { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string Descriptionforoptionchoosen { get; set; }
    
        public virtual InterviewCandidate InterviewCandidate { get; set; }
    }
}
