//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientProject
    {
        public int CL_ProjectID { get; set; }
        public Nullable<int> Proj_ProjectID { get; set; }
        public Nullable<int> Accountid { get; set; }
        public string ClientProjTitle { get; set; }
        public string ClientProjDesc { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
