//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientProjectsTask
    {
        public int CL_ProjectsTasksID { get; set; }
        public Nullable<int> Accountid { get; set; }
        public Nullable<int> rol_roleid { get; set; }
        public Nullable<int> acc_specifictaskid { get; set; }
    }
}
