//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentType
    {
        public int ComponentTypeId { get; set; }
        public string ComponentType1 { get; set; }
        public Nullable<System.DateTime> Com_CreatedDate { get; set; }
        public Nullable<int> Com_CreatedBy { get; set; }
        public Nullable<System.DateTime> Com_ModifiedDate { get; set; }
        public Nullable<int> Com_ModifiedBy { get; set; }
        public Nullable<bool> Com_isDeleted { get; set; }
        public Nullable<bool> Com_ActiveStatus { get; set; }
    }
}
