//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentType
    {
        public int ContentTypeId { get; set; }
        public string ContentTitle { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Con_ActiveStatus { get; set; }
        public Nullable<System.DateTime> Con_CreatedDate { get; set; }
        public Nullable<int> Con_CreatedBy { get; set; }
        public Nullable<System.DateTime> Con_ModifiedDate { get; set; }
        public Nullable<int> Con_ModifiedBy { get; set; }
        public Nullable<bool> Con_isDeleted { get; set; }
    }
}
