//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentType
    {
        public int DocumentTypeId { get; set; }
        public string DocumentTitle { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Doc_ActiveStatus { get; set; }
        public Nullable<System.DateTime> Doc_CreatedDate { get; set; }
        public Nullable<int> Doc_CreatedBy { get; set; }
        public Nullable<System.DateTime> Doc_ModifiedDate { get; set; }
        public Nullable<int> Doc_ModifiedBy { get; set; }
        public Nullable<bool> Doc_isDeleted { get; set; }
    }
}
