//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalarySlip
    {
        public int EmpSalarySlipID { get; set; }
        public Nullable<int> Epmss_UserID { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> YEAR { get; set; }
    }
}
