//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalaryComponent
    {
        public int EmpSalCompId { get; set; }
        public Nullable<int> EmpSC_AccountID { get; set; }
        public string ComponentTitle { get; set; }
        public string ComponentDescription { get; set; }
        public Nullable<int> ComponentTypeId { get; set; }
        public Nullable<bool> EmpSC_ActiveStatus { get; set; }
        public Nullable<int> EmpSC_Version { get; set; }
        public Nullable<System.DateTime> EmpSC_CreatedDate { get; set; }
        public Nullable<int> EmpSC_CreatedBy { get; set; }
        public Nullable<System.DateTime> EmpSC_ModifiedDate { get; set; }
        public Nullable<int> EmpSC_ModifiedBy { get; set; }
        public Nullable<bool> EmpSC_isDeleted { get; set; }
    }
}
