//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeBankDetail
    {
        public int EmpBankID { get; set; }
        public Nullable<int> EmpB_UserID { get; set; }
        public Nullable<long> BANK_No { get; set; }
        public string PAN_No { get; set; }
        public Nullable<long> UAN_No { get; set; }
        public string PF_No { get; set; }
        public string ESI_No { get; set; }
        public Nullable<int> PayModeID { get; set; }
    }
}
