//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalaryStructure
    {
        public int Emps_StructureID { get; set; }
        public Nullable<int> Emps_UserID { get; set; }
        public Nullable<int> WorkingDays { get; set; }
        public Nullable<int> WorkedDays { get; set; }
        public Nullable<int> Payable { get; set; }
        public Nullable<System.DateTime> SalaryMonth { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
        public Nullable<decimal> CTC { get; set; }
        public Nullable<bool> Ess_ActiveStatus { get; set; }
        public Nullable<int> Ess_Version { get; set; }
        public Nullable<System.DateTime> Ess_CreatedDate { get; set; }
        public Nullable<int> Ess_CreatedBy { get; set; }
        public Nullable<System.DateTime> Ess_ModifiedDate { get; set; }
        public Nullable<int> Ess_ModifiedBy { get; set; }
        public Nullable<bool> Ess_isDeleted { get; set; }
    }
}
