//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalaryStructureDetail
    {
        public int EmpssdetailId { get; set; }
        public Nullable<int> EmpSalCompId { get; set; }
        public Nullable<int> Emps_StructureId { get; set; }
        public Nullable<bool> EssD_ActiveStatus { get; set; }
        public Nullable<int> EssD_Version { get; set; }
        public Nullable<System.DateTime> EssD_CreatedDate { get; set; }
        public Nullable<int> EssD_CreatedBy { get; set; }
        public Nullable<System.DateTime> EssD_ModifiedDate { get; set; }
        public Nullable<int> EssD_ModifiedBy { get; set; }
        public Nullable<bool> EssD_isDeleted { get; set; }
    }
}
