//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_LeaveComments
    {
        public int History_CommentId { get; set; }
        public int Usrl_LeaveId { get; set; }
        public int Userid { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<int> Action { get; set; }
        public string Comments { get; set; }
        public Nullable<int> managerid { get; set; }
    }
}
