//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_Role
    {
        public int History_Role_ID { get; set; }
        public int History_Rol_RoleID { get; set; }
        public int History_Rol_AccountID { get; set; }
        public string History_Rol_RoleCode { get; set; }
        public string History_Rol_RoleName { get; set; }
        public string History_Rol_RoleDescription { get; set; }
        public bool History_Rol_ActiveStatus { get; set; }
        public int History_Rol_Version { get; set; }
        public System.DateTime History_Rol_CreatedDate { get; set; }
        public int History_Rol_createdBy { get; set; }
        public Nullable<System.DateTime> History_Rol_ModifiedDate { get; set; }
        public Nullable<int> History_Rol_ModifiedBy { get; set; }
        public bool History_Rol_isDeleted { get; set; }
    }
}
