//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_UserType
    {
        public int History_UserType_ID { get; set; }
        public int History_UsT_UserTypeID { get; set; }
        public int History_AccountID { get; set; }
        public string History_UsT_UserTypeCode { get; set; }
        public string History_UsT_UserType { get; set; }
        public string History_UsT_UserTypeDescription { get; set; }
        public bool History_UsT_ActiveStatus { get; set; }
        public int History_UsT_Version { get; set; }
        public System.DateTime History_UsT_CreatedDate { get; set; }
        public int History_UsT_CreatedBy { get; set; }
        public Nullable<System.DateTime> History_UsT_ModifiedDate { get; set; }
        public Nullable<int> History_UsT_ModifiedBy { get; set; }
        public bool History_UsT_isDeleted { get; set; }
    }
}
