//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_Projects
    {
        public int History_Project_ID { get; set; }
        public int History_Proj_ProjectID { get; set; }
        public int History_Proj_AccountID { get; set; }
        public string History_Proj_ProjectCode { get; set; }
        public string History_Proj_ProjectName { get; set; }
        public string History_Proj_ProjectDescription { get; set; }
        public System.DateTime History_Proj_StartDate { get; set; }
        public Nullable<System.DateTime> History_Proj_EndDate { get; set; }
        public bool History_Proj_ActiveStatus { get; set; }
        public short History_Proj_Version { get; set; }
        public System.DateTime History_Proj_CreatedDate { get; set; }
        public int History_Proj_CreatedBy { get; set; }
        public Nullable<System.DateTime> History_Proj_ModifiedDate { get; set; }
        public Nullable<int> History_Proj_ModifiedBy { get; set; }
        public bool History_Proj_isDeleted { get; set; }
    }
}
