//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_Account
    {
        public int History_Account_AccountID { get; set; }
        public int History_Acc_AccountID { get; set; }
        public string History_Acc_AccountCode { get; set; }
        public string History_Acc_AccountName { get; set; }
        public string History_Acc_AccountDescription { get; set; }
        public string History_Acc_EmailID { get; set; }
        public string History_Acc_MobileNumber { get; set; }
        public string History_Acc_PhoneNumber { get; set; }
        public string History_Acc_CompanyLogo { get; set; }
        public bool History_Acc_ActiveStatus { get; set; }
        public short History_Acc_Version { get; set; }
        public System.DateTime History_Acc_CreatedDate { get; set; }
        public int History_Acc_CreatedBy { get; set; }
        public Nullable<System.DateTime> History_Acc_ModifiedDate { get; set; }
        public Nullable<int> History_Acc_ModifiedBy { get; set; }
        public bool History_Acc_isDeleted { get; set; }
    }
}
