//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_LeaveScheme
    {
        public int History_LeaveScheme_ID { get; set; }
        public int History_LSchm_LeaveSchemeID { get; set; }
        public int History_LSchm_LeaveTypeID { get; set; }
        public int History_LSchm_UserTypeID { get; set; }
        public string History_LSchm_LeaveFrequency { get; set; }
        public int History_LSchm_AccountID { get; set; }
        public string History_LSchm_LeaveSchemeCode { get; set; }
        public string History_LSchm_LeaveScheme { get; set; }
        public string History_LSchm_LeaveSchemeDescription { get; set; }
        public short History_LSchm_LeaveCount { get; set; }
        public bool History_LSchm_ActiveStatus { get; set; }
        public short History_LSchm_Version { get; set; }
        public System.DateTime History_LSchm_CreatedDate { get; set; }
        public int History_LSchm_CreatedBy { get; set; }
        public Nullable<System.DateTime> History_LSchm_ModifiedDate { get; set; }
        public Nullable<int> History_LSchm_ModifiedBy { get; set; }
        public bool History_LSchm_isDeleted { get; set; }
    }
}
