//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_LeaveType
    {
        public int History_LeaveType_ID { get; set; }
        public int History_LTyp_LeaveTypeID { get; set; }
        public int History_LTyp_AccountID { get; set; }
        public string History_LTyp_LeaveType { get; set; }
        public string History_LTyp_LeaveTypeDescription { get; set; }
        public bool History_LTyp_ActiveStatus { get; set; }
        public short History_LTyp_Version { get; set; }
        public System.DateTime History_LTyp_CreatedDate { get; set; }
        public int History_LTyp_CreatedBy { get; set; }
        public Nullable<System.DateTime> History_LTyp_ModifiedDate { get; set; }
        public Nullable<int> History_LTyp_ModifiedBy { get; set; }
        public bool History_LTyp_isDeleted { get; set; }
    }
}
