//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_UserProjects
    {
        public int HUProj_UserProjectID { get; set; }
        public int HUProj_ProjectID { get; set; }
        public int HUProj_UserID { get; set; }
        public System.DateTime HUProj_StartDate { get; set; }
        public Nullable<System.DateTime> HUProj_EndDate { get; set; }
        public byte HUProj_ParticipationPercentage { get; set; }
        public bool HUProj_ActiveStatus { get; set; }
        public short HUProj_Version { get; set; }
        public System.DateTime HUProj_CreatedDate { get; set; }
        public int HUProj_CreatedBy { get; set; }
        public Nullable<System.DateTime> HUProj_ModifiedDate { get; set; }
        public Nullable<int> HUProj_ModifiedBy { get; set; }
        public bool HUProj_isDeleted { get; set; }
    }
}
