//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HolidayCalendar
    {
        public int HolidayCalendarID { get; set; }
        public int AccountID { get; set; }
        public string HolidayName { get; set; }
        public int Year { get; set; }
        public System.DateTime HolidayDate { get; set; }
        public bool isOptionalHoliday { get; set; }
        public bool isActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> CL_ProjectID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
