//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveType
    {
        public int LTyp_LeaveTypeID { get; set; }
        public int LTyp_AccountID { get; set; }
        public string LTyp_LeaveType { get; set; }
        public string LTyp_LeaveTypeDescription { get; set; }
        public bool LTyp_ActiveStatus { get; set; }
        public short LTyp_Version { get; set; }
        public System.DateTime LTyp_CreatedDate { get; set; }
        public int LTyp_CreatedBy { get; set; }
        public Nullable<System.DateTime> LTyp_ModifiedDate { get; set; }
        public Nullable<int> LTyp_ModifiedBy { get; set; }
        public bool LTyp_isDeleted { get; set; }
    }
}
