//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveScheme
    {
        public int LSchm_LeaveSchemeID { get; set; }
        public int LSchm_LeaveTypeID { get; set; }
        public int LSchm_UserTypeID { get; set; }
        public string LSchm_LeaveFrequency { get; set; }
        public int LSchm_AccountID { get; set; }
        public string LSchm_LeaveSchemeCode { get; set; }
        public string LSchm_LeaveScheme { get; set; }
        public string LSchm_LeaveSchemeDescription { get; set; }
        public Nullable<double> LSchm_LeaveCount { get; set; }
        public bool LSchm_ActiveStatus { get; set; }
        public Nullable<short> LSchm_Version { get; set; }
        public System.DateTime LSchm_CreatedDate { get; set; }
        public int LSchm_CreatedBy { get; set; }
        public Nullable<System.DateTime> LSchm_ModifiedDate { get; set; }
        public Nullable<int> LSchm_ModifiedBy { get; set; }
        public bool LSchm_isDeleted { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
    }
}
