//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Sub_Module
    {
        public int Sub_ModuleID { get; set; }
        public int Mod_ModuleID { get; set; }
        public string Sub_ModuleCode { get; set; }
        public string Sub_ModuleName { get; set; }
        public string Sub_Description { get; set; }
        public bool Sub_ActiveStatus { get; set; }
        public short Sub_Version { get; set; }
        public System.DateTime Sub_CreatedDate { get; set; }
        public int Sub_CreatedBy { get; set; }
        public Nullable<System.DateTime> Sub_ModifiedDate { get; set; }
        public Nullable<int> Sub_ModifiedBy { get; set; }
        public bool Sub_isDeleted { get; set; }
        public Nullable<int> Orderby { get; set; }
    }
}
