//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Module
    {
        public int Mod_ModuleID { get; set; }
        public string Mod_ModuleCode { get; set; }
        public string Mod_ModuleName { get; set; }
        public string Mod_Description { get; set; }
        public bool Mod_ActiveStatus { get; set; }
        public short Mod_Version { get; set; }
        public System.DateTime Mod_CreatedDate { get; set; }
        public int Mod_CreatedBy { get; set; }
        public Nullable<System.DateTime> Mod_ModifiedDate { get; set; }
        public Nullable<int> Mod_ModifiedBy { get; set; }
        public bool Mod_isDeleted { get; set; }
    }
}
