//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy
    {
        public int PolicyId { get; set; }
        public string PolicyTitle { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> Is_Css { get; set; }
        public string PolicyDescription { get; set; }
        public Nullable<bool> Pol_ActiveStatus { get; set; }
        public Nullable<System.DateTime> Pol_CreatedDate { get; set; }
        public Nullable<int> Pol_CreatedBy { get; set; }
        public Nullable<System.DateTime> Pol_ModifiedDate { get; set; }
        public Nullable<int> Pol_ModifiedBy { get; set; }
        public Nullable<bool> Pol_isDeleted { get; set; }
    }
}
