//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int Rol_RoleID { get; set; }
        public int Rol_AccountID { get; set; }
        public string Rol_RoleCode { get; set; }
        public Nullable<int> Rol_RoleName { get; set; }
        public string Rol_RoleDescription { get; set; }
        public bool Rol_ActiveStatus { get; set; }
        public int Rol_Version { get; set; }
        public System.DateTime Rol_CreatedDate { get; set; }
        public int Rol_createdBy { get; set; }
        public Nullable<System.DateTime> Rol_ModifiedDate { get; set; }
        public Nullable<int> Rol_ModifiedBy { get; set; }
        public bool Rol_isDeleted { get; set; }
        public Nullable<bool> IsManagerRole { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Role Roles1 { get; set; }
        public virtual Role Role1 { get; set; }
    }
}
