//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialMedia
    {
        public int SocialMediaId { get; set; }
        public Nullable<int> Sm_AccountID { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public Nullable<System.DateTime> Sm_CreatedDate { get; set; }
        public Nullable<int> Sm_CreatedBy { get; set; }
        public Nullable<System.DateTime> Sm_ModifiedDate { get; set; }
        public Nullable<int> Sm_ModifiedBy { get; set; }
        public Nullable<bool> Sm_isDeleted { get; set; }
        public Nullable<bool> Sm_ActiveStatus { get; set; }
    }
}
