//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubPolicy
    {
        public int SubPolicyId { get; set; }
        public Nullable<int> PolicyId { get; set; }
        public string SubPolicyTitle { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> Is_Css { get; set; }
        public string Purpose { get; set; }
        public Nullable<bool> SPol_ActiveStatus { get; set; }
        public Nullable<System.DateTime> SPol_CreatedDate { get; set; }
        public Nullable<int> SPol_CreatedBy { get; set; }
        public Nullable<System.DateTime> SPol_ModifiedDate { get; set; }
        public Nullable<int> SPol_ModifiedBy { get; set; }
        public Nullable<bool> SPol_isDeleted { get; set; }
    }
}
