//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubPolicyDocument
    {
        public int SubPolicyDocumentId { get; set; }
        public Nullable<int> SubPolicyId { get; set; }
        public string SubPolicyDocumenTitle { get; set; }
        public Nullable<int> DocumentTypeId { get; set; }
        public Nullable<int> ContentTypeId { get; set; }
        public string DocumentTitle { get; set; }
        public byte[] DocumentFile { get; set; }
        public Nullable<bool> SubP_ActiveStatus { get; set; }
        public Nullable<System.DateTime> SubP_CreatedDate { get; set; }
        public Nullable<int> SubP_CreatedBy { get; set; }
        public Nullable<System.DateTime> SubP_ModifiedDate { get; set; }
        public Nullable<int> SubP_ModifiedBy { get; set; }
        public Nullable<bool> SubP_isDeleted { get; set; }
    }
}
