//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDetail
    {
        public int TaskDetailsID { get; set; }
        public int TimesheetID { get; set; }
        public int TaskID { get; set; }
        public Nullable<decimal> HoursWorked { get; set; }
        public Nullable<System.DateTime> TaskDate { get; set; }
        public Nullable<int> Proj_SpecificTaskId { get; set; }
        public Nullable<int> projectid { get; set; }
    }
}
