//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.TicketImages = new HashSet<TicketImage>();
        }
    
        public int TID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Description { get; set; }
        public Nullable<int> TypeOfIssue { get; set; }
        public Nullable<System.DateTime> Ticket_raise_date { get; set; }
        public Nullable<System.DateTime> Ticket_Forecast_date { get; set; }
        public Nullable<System.DateTime> Ticket_Closed_date { get; set; }
        public Nullable<int> ClosedBy { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketImage> TicketImages { get; set; }
    }
}
