//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheet_Comments
    {
        public int Timesheet_CommentId { get; set; }
        public int Timesheetid { get; set; }
        public int Userid { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<int> Action { get; set; }
        public string Comments { get; set; }
        public Nullable<int> managerid_L1 { get; set; }
        public Nullable<int> managerid_L2 { get; set; }
    }
}
