//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSkill
    {
        public int Usr_SkillId { get; set; }
        public Nullable<int> Usr_UserId { get; set; }
        public Nullable<int> SkillId { get; set; }
        public string Experience { get; set; }
        public Nullable<System.DateTime> Usk_CreatedDate { get; set; }
        public Nullable<System.DateTime> Usk_ModifiedDate { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
        public Nullable<int> StatusID { get; set; }
    }
}
