//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserType()
        {
            this.Users = new HashSet<User>();
        }
    
        public int UsT_UserTypeID { get; set; }
        public int UsT_AccountID { get; set; }
        public string UsT_UserTypeCode { get; set; }
        public string UsT_UserType { get; set; }
        public string UsT_UserTypeDescription { get; set; }
        public bool UsT_ActiveStatus { get; set; }
        public int UsT_Version { get; set; }
        public System.DateTime UsT_CreatedDate { get; set; }
        public int UsT_CreatedBy { get; set; }
        public Nullable<System.DateTime> UsT_ModifiedDate { get; set; }
        public Nullable<int> UsT_ModifiedBy { get; set; }
        public bool UsT_isDeleted { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
