//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLeaveTypeConsumed
    {
        public int Usrlt_TypeConsumeId { get; set; }
        public Nullable<int> Usrl_LeaveId { get; set; }
        public Nullable<int> LSchm_LeaveSchemeID { get; set; }
        public Nullable<int> No_Of_Days { get; set; }
    }
}
