//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSalaryCalculation
    {
        public int UserSalaryCalculationsId { get; set; }
        public string UserName { get; set; }
        public int HireType { get; set; }
        public Nullable<int> VisaType { get; set; }
        public string AnnualSalary { get; set; }
        public string AnnualSalaryPerhour { get; set; }
        public string PayrollTaxes { get; set; }
        public string PayrollTaxesPerHour { get; set; }
        public string H1BFee { get; set; }
        public string H1BFeePerHour { get; set; }
        public string GCFee { get; set; }
        public string GCFeePerHour { get; set; }
        public string Insurance { get; set; }
        public string InsurancePerHour { get; set; }
        public string C2WeeksPaidVocation { get; set; }
        public string C2WeeksPaidVocationPerHour { get; set; }
        public string Holidays { get; set; }
        public string HolidaysPerHour { get; set; }
        public string AdministrativeCost { get; set; }
        public string AdministrativeCostPerHour { get; set; }
        public string Relocation { get; set; }
        public string RelocationPerHour { get; set; }
        public string PaidBench { get; set; }
        public string PaidBenchPerHour { get; set; }
        public string Bonus { get; set; }
        public string BonusPerHour { get; set; }
        public string Total { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
