//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProject
    {
        public int UProj_UserProjectID { get; set; }
        public int UProj_ProjectID { get; set; }
        public int UProj_UserID { get; set; }
        public System.DateTime UProj_StartDate { get; set; }
        public Nullable<System.DateTime> UProj_EndDate { get; set; }
        public byte UProj_ParticipationPercentage { get; set; }
        public bool UProj_ActiveStatus { get; set; }
        public short UProj_Version { get; set; }
        public System.DateTime UProj_CreatedDate { get; set; }
        public int UProj_CreatedBy { get; set; }
        public Nullable<System.DateTime> UProj_ModifiedDate { get; set; }
        public Nullable<int> UProj_ModifiedBy { get; set; }
        public bool UProj_isDeleted { get; set; }
        public Nullable<int> UProj_L1_ManagerId { get; set; }
        public Nullable<int> UProj_L2_ManagerId { get; set; }
        public Nullable<bool> Is_L1_Manager { get; set; }
        public Nullable<bool> Is_L2_Manager { get; set; }
        public Nullable<int> ClientprojID { get; set; }
        public Nullable<int> TimesheetMode { get; set; }
        public Nullable<bool> IsDirectManager { get; set; }
        public Nullable<bool> isclientcalendar { get; set; }
    }
}
