//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersForProject
    {
        public int Ufp_UsersForProjectsID { get; set; }
        public int Ufp_ProjectID { get; set; }
        public int Ufp_UserID { get; set; }
        public System.DateTime Ufp_StartDate { get; set; }
        public Nullable<System.DateTime> Ufp_EndDate { get; set; }
        public Nullable<int> Ufp_ParticipationPercentage { get; set; }
        public bool Ufp_ActiveStatus { get; set; }
        public short Ufp_Version { get; set; }
        public System.DateTime Ufp_CreatedDate { get; set; }
        public int Ufp_CreatedBy { get; set; }
        public Nullable<System.DateTime> Ufp_ModifiedDate { get; set; }
        public Nullable<int> Ufp_ModifiedBy { get; set; }
        public bool Ufp_isDeleted { get; set; }
    }
}
