//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSocialMediaProfile
    {
        public int SocialMediaProfileId { get; set; }
        public Nullable<int> Usmp_UserID { get; set; }
        public Nullable<int> Usmp_SocialMediaId { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> Usmp_CreatedDate { get; set; }
        public Nullable<System.DateTime> Usmp_ModifiedDate { get; set; }
    }
}
