//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTitle
    {
        public int Usr_Titleid { get; set; }
        public string TitlePrefix { get; set; }
        public Nullable<int> Acc_AccountID { get; set; }
    }
}
