//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USSalaryComponent
    {
        public int USSalaryComponentID { get; set; }
        public string USSalaryComponent1 { get; set; }
        public string USSalaryComponentValue { get; set; }
        public Nullable<bool> StatusID { get; set; }
    }
}
