//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evolutyz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisaType
    {
        public int VisaTypeID { get; set; }
        public string VisaType1 { get; set; }
        public string VisaTypeShortForm { get; set; }
        public Nullable<bool> StatusID { get; set; }
    }
}
